### ISSUE TITLE
Portable HTML Page is Broken in Chrome

### ISSUE THREAD

**Issue by rarcher** [ericwoodruff/passwordhasherplus#34]
The latest version of Google Chrome seems to block Javascript in the portable HTML page, rendering it effectively useless.

OS is Ubuntu Linux, if that matters.

**Comment by Pendrokar** [comment]
It doesn't matter. I see the same on Ubuntu Linux 16.04 and Windows 10.

**Comment by bscan** [comment]
If you need passwords in the meantime, the "Download portable html page" button will insert the dependency sources into an html file. However, you need the functioning version of the page for this to be working. I downloaded one and put it here:

https://cdn.rawgit.com/bscan/passwordhasherplus/cd0d99bc/passhashplus.html

**Comment by Pendrokar** [comment]
This issue got fixed with #36

**Comment by rarcher** [comment]
Confirmed. It is working here as well.
